name: Site
version: 2.0.3
description: Site plugin to display entries content on the website frontend.
icon:
  name: globe
  set: fontawesome|solid  
category: content
author:
  name: Sergey Romanenko
  email: awilum@msn.com
  url: https://awilum.github.io
homepage: https://awilum.github.io/flextype/downloads/extend/plugins/site
bugs: https://github.com/flextype-plugins/site/issues
license: MIT

dependencies:
  flextype: "^1.0.0-alpha.1"