name: Site
version: 1.10.0
description: Site plugin to display entries content on the website frontend.
icon:
  name: globe
  set: "fontawesome|solid"
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/site
bugs: https://github.com/flextype-plugins/site/issues
license: MIT

dependencies:
  flextype: 0.9.15
  twig: '>=2.0.0'
