name: Site
version: 1.0.0
description: Site plugin to display entries content on the website frontend.
icon: fas fa-globe
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/site
bugs: https://github.com/flextype-plugins/site/issues
license: MIT

dependencies:
  flextype: 0.9.7
  plugins:
    twig: 1.0.0
